//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Practica1IPC2_Whizz_Hard_Books_.WebServiceSource {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultasBibliotecaSoap", Namespace="http://tempuri.org/")]
    public partial class ConsultasBiblioteca : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetContactOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agregar_LibroOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agregar_AutorOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agregar_MiembroOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agregar_ReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Agregar_prestamoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Lista_AutoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback Lista_libros_disponiblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Lista_libros_PrestadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback Max_Lista_librosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevolucionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultasBiblioteca() {
            this.Url = global::Practica1IPC2_Whizz_Hard_Books_.Properties.Settings.Default.Practica1IPC2_Whizz_Hard_Books__WebServiceSource_ConsultasBiblioteca;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetContactCompletedEventHandler GetContactCompleted;
        
        /// <remarks/>
        public event Agregar_LibroCompletedEventHandler Agregar_LibroCompleted;
        
        /// <remarks/>
        public event Agregar_AutorCompletedEventHandler Agregar_AutorCompleted;
        
        /// <remarks/>
        public event Agregar_MiembroCompletedEventHandler Agregar_MiembroCompleted;
        
        /// <remarks/>
        public event Agregar_ReservaCompletedEventHandler Agregar_ReservaCompleted;
        
        /// <remarks/>
        public event Agregar_prestamoCompletedEventHandler Agregar_prestamoCompleted;
        
        /// <remarks/>
        public event Lista_AutoresCompletedEventHandler Lista_AutoresCompleted;
        
        /// <remarks/>
        public event Lista_libros_disponiblesCompletedEventHandler Lista_libros_disponiblesCompleted;
        
        /// <remarks/>
        public event Lista_libros_PrestadosCompletedEventHandler Lista_libros_PrestadosCompleted;
        
        /// <remarks/>
        public event Max_Lista_librosCompletedEventHandler Max_Lista_librosCompleted;
        
        /// <remarks/>
        public event ConsultaCompletedEventHandler ConsultaCompleted;
        
        /// <remarks/>
        public event DevolucionCompletedEventHandler DevolucionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetContact", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetContact(string id) {
            object[] results = this.Invoke("GetContact", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetContactAsync(string id) {
            this.GetContactAsync(id, null);
        }
        
        /// <remarks/>
        public void GetContactAsync(string id, object userState) {
            if ((this.GetContactOperationCompleted == null)) {
                this.GetContactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactOperationCompleted);
            }
            this.InvokeAsync("GetContact", new object[] {
                        id}, this.GetContactOperationCompleted, userState);
        }
        
        private void OnGetContactOperationCompleted(object arg) {
            if ((this.GetContactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContactCompleted(this, new GetContactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agregar_Libro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Agregar_Libro(int cod_libro, int cod_autor, string titulo, int pags, string tema) {
            object[] results = this.Invoke("Agregar_Libro", new object[] {
                        cod_libro,
                        cod_autor,
                        titulo,
                        pags,
                        tema});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Agregar_LibroAsync(int cod_libro, int cod_autor, string titulo, int pags, string tema) {
            this.Agregar_LibroAsync(cod_libro, cod_autor, titulo, pags, tema, null);
        }
        
        /// <remarks/>
        public void Agregar_LibroAsync(int cod_libro, int cod_autor, string titulo, int pags, string tema, object userState) {
            if ((this.Agregar_LibroOperationCompleted == null)) {
                this.Agregar_LibroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregar_LibroOperationCompleted);
            }
            this.InvokeAsync("Agregar_Libro", new object[] {
                        cod_libro,
                        cod_autor,
                        titulo,
                        pags,
                        tema}, this.Agregar_LibroOperationCompleted, userState);
        }
        
        private void OnAgregar_LibroOperationCompleted(object arg) {
            if ((this.Agregar_LibroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agregar_LibroCompleted(this, new Agregar_LibroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agregar_Autor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Agregar_Autor(string nombre, string apellido) {
            object[] results = this.Invoke("Agregar_Autor", new object[] {
                        nombre,
                        apellido});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Agregar_AutorAsync(string nombre, string apellido) {
            this.Agregar_AutorAsync(nombre, apellido, null);
        }
        
        /// <remarks/>
        public void Agregar_AutorAsync(string nombre, string apellido, object userState) {
            if ((this.Agregar_AutorOperationCompleted == null)) {
                this.Agregar_AutorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregar_AutorOperationCompleted);
            }
            this.InvokeAsync("Agregar_Autor", new object[] {
                        nombre,
                        apellido}, this.Agregar_AutorOperationCompleted, userState);
        }
        
        private void OnAgregar_AutorOperationCompleted(object arg) {
            if ((this.Agregar_AutorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agregar_AutorCompleted(this, new Agregar_AutorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agregar_Miembro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Agregar_Miembro(string nombre, int DPI, string direccion, int telefono) {
            object[] results = this.Invoke("Agregar_Miembro", new object[] {
                        nombre,
                        DPI,
                        direccion,
                        telefono});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Agregar_MiembroAsync(string nombre, int DPI, string direccion, int telefono) {
            this.Agregar_MiembroAsync(nombre, DPI, direccion, telefono, null);
        }
        
        /// <remarks/>
        public void Agregar_MiembroAsync(string nombre, int DPI, string direccion, int telefono, object userState) {
            if ((this.Agregar_MiembroOperationCompleted == null)) {
                this.Agregar_MiembroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregar_MiembroOperationCompleted);
            }
            this.InvokeAsync("Agregar_Miembro", new object[] {
                        nombre,
                        DPI,
                        direccion,
                        telefono}, this.Agregar_MiembroOperationCompleted, userState);
        }
        
        private void OnAgregar_MiembroOperationCompleted(object arg) {
            if ((this.Agregar_MiembroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agregar_MiembroCompleted(this, new Agregar_MiembroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agregar_Reserva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Agregar_Reserva(int cod_miembro, int cod_libro) {
            object[] results = this.Invoke("Agregar_Reserva", new object[] {
                        cod_miembro,
                        cod_libro});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Agregar_ReservaAsync(int cod_miembro, int cod_libro) {
            this.Agregar_ReservaAsync(cod_miembro, cod_libro, null);
        }
        
        /// <remarks/>
        public void Agregar_ReservaAsync(int cod_miembro, int cod_libro, object userState) {
            if ((this.Agregar_ReservaOperationCompleted == null)) {
                this.Agregar_ReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregar_ReservaOperationCompleted);
            }
            this.InvokeAsync("Agregar_Reserva", new object[] {
                        cod_miembro,
                        cod_libro}, this.Agregar_ReservaOperationCompleted, userState);
        }
        
        private void OnAgregar_ReservaOperationCompleted(object arg) {
            if ((this.Agregar_ReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agregar_ReservaCompleted(this, new Agregar_ReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agregar_prestamo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Agregar_prestamo(string fecha, int cod_miembro, int cod_registro_libro) {
            object[] results = this.Invoke("Agregar_prestamo", new object[] {
                        fecha,
                        cod_miembro,
                        cod_registro_libro});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Agregar_prestamoAsync(string fecha, int cod_miembro, int cod_registro_libro) {
            this.Agregar_prestamoAsync(fecha, cod_miembro, cod_registro_libro, null);
        }
        
        /// <remarks/>
        public void Agregar_prestamoAsync(string fecha, int cod_miembro, int cod_registro_libro, object userState) {
            if ((this.Agregar_prestamoOperationCompleted == null)) {
                this.Agregar_prestamoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregar_prestamoOperationCompleted);
            }
            this.InvokeAsync("Agregar_prestamo", new object[] {
                        fecha,
                        cod_miembro,
                        cod_registro_libro}, this.Agregar_prestamoOperationCompleted, userState);
        }
        
        private void OnAgregar_prestamoOperationCompleted(object arg) {
            if ((this.Agregar_prestamoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Agregar_prestamoCompleted(this, new Agregar_prestamoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Lista_Autores", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Lista_Autores() {
            object[] results = this.Invoke("Lista_Autores", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Lista_AutoresAsync() {
            this.Lista_AutoresAsync(null);
        }
        
        /// <remarks/>
        public void Lista_AutoresAsync(object userState) {
            if ((this.Lista_AutoresOperationCompleted == null)) {
                this.Lista_AutoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLista_AutoresOperationCompleted);
            }
            this.InvokeAsync("Lista_Autores", new object[0], this.Lista_AutoresOperationCompleted, userState);
        }
        
        private void OnLista_AutoresOperationCompleted(object arg) {
            if ((this.Lista_AutoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Lista_AutoresCompleted(this, new Lista_AutoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Lista_libros_disponibles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Lista_libros_disponibles() {
            object[] results = this.Invoke("Lista_libros_disponibles", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Lista_libros_disponiblesAsync() {
            this.Lista_libros_disponiblesAsync(null);
        }
        
        /// <remarks/>
        public void Lista_libros_disponiblesAsync(object userState) {
            if ((this.Lista_libros_disponiblesOperationCompleted == null)) {
                this.Lista_libros_disponiblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLista_libros_disponiblesOperationCompleted);
            }
            this.InvokeAsync("Lista_libros_disponibles", new object[0], this.Lista_libros_disponiblesOperationCompleted, userState);
        }
        
        private void OnLista_libros_disponiblesOperationCompleted(object arg) {
            if ((this.Lista_libros_disponiblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Lista_libros_disponiblesCompleted(this, new Lista_libros_disponiblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Lista_libros_Prestados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Lista_libros_Prestados() {
            object[] results = this.Invoke("Lista_libros_Prestados", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Lista_libros_PrestadosAsync() {
            this.Lista_libros_PrestadosAsync(null);
        }
        
        /// <remarks/>
        public void Lista_libros_PrestadosAsync(object userState) {
            if ((this.Lista_libros_PrestadosOperationCompleted == null)) {
                this.Lista_libros_PrestadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLista_libros_PrestadosOperationCompleted);
            }
            this.InvokeAsync("Lista_libros_Prestados", new object[0], this.Lista_libros_PrestadosOperationCompleted, userState);
        }
        
        private void OnLista_libros_PrestadosOperationCompleted(object arg) {
            if ((this.Lista_libros_PrestadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Lista_libros_PrestadosCompleted(this, new Lista_libros_PrestadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Max_Lista_libros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Max_Lista_libros() {
            object[] results = this.Invoke("Max_Lista_libros", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Max_Lista_librosAsync() {
            this.Max_Lista_librosAsync(null);
        }
        
        /// <remarks/>
        public void Max_Lista_librosAsync(object userState) {
            if ((this.Max_Lista_librosOperationCompleted == null)) {
                this.Max_Lista_librosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMax_Lista_librosOperationCompleted);
            }
            this.InvokeAsync("Max_Lista_libros", new object[0], this.Max_Lista_librosOperationCompleted, userState);
        }
        
        private void OnMax_Lista_librosOperationCompleted(object arg) {
            if ((this.Max_Lista_librosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Max_Lista_librosCompleted(this, new Max_Lista_librosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Consulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Consulta(string nombre) {
            object[] results = this.Invoke("Consulta", new object[] {
                        nombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaAsync(string nombre) {
            this.ConsultaAsync(nombre, null);
        }
        
        /// <remarks/>
        public void ConsultaAsync(string nombre, object userState) {
            if ((this.ConsultaOperationCompleted == null)) {
                this.ConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaOperationCompleted);
            }
            this.InvokeAsync("Consulta", new object[] {
                        nombre}, this.ConsultaOperationCompleted, userState);
        }
        
        private void OnConsultaOperationCompleted(object arg) {
            if ((this.ConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCompleted(this, new ConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Devolucion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Devolucion(string fecha, int cod_miembro, int cod_registro_libro) {
            object[] results = this.Invoke("Devolucion", new object[] {
                        fecha,
                        cod_miembro,
                        cod_registro_libro});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DevolucionAsync(string fecha, int cod_miembro, int cod_registro_libro) {
            this.DevolucionAsync(fecha, cod_miembro, cod_registro_libro, null);
        }
        
        /// <remarks/>
        public void DevolucionAsync(string fecha, int cod_miembro, int cod_registro_libro, object userState) {
            if ((this.DevolucionOperationCompleted == null)) {
                this.DevolucionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevolucionOperationCompleted);
            }
            this.InvokeAsync("Devolucion", new object[] {
                        fecha,
                        cod_miembro,
                        cod_registro_libro}, this.DevolucionOperationCompleted, userState);
        }
        
        private void OnDevolucionOperationCompleted(object arg) {
            if ((this.DevolucionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevolucionCompleted(this, new DevolucionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetContactCompletedEventHandler(object sender, GetContactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetContactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetContactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Agregar_LibroCompletedEventHandler(object sender, Agregar_LibroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agregar_LibroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agregar_LibroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Agregar_AutorCompletedEventHandler(object sender, Agregar_AutorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agregar_AutorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agregar_AutorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Agregar_MiembroCompletedEventHandler(object sender, Agregar_MiembroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agregar_MiembroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agregar_MiembroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Agregar_ReservaCompletedEventHandler(object sender, Agregar_ReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agregar_ReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agregar_ReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Agregar_prestamoCompletedEventHandler(object sender, Agregar_prestamoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Agregar_prestamoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Agregar_prestamoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Lista_AutoresCompletedEventHandler(object sender, Lista_AutoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lista_AutoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Lista_AutoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Lista_libros_disponiblesCompletedEventHandler(object sender, Lista_libros_disponiblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lista_libros_disponiblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Lista_libros_disponiblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Lista_libros_PrestadosCompletedEventHandler(object sender, Lista_libros_PrestadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Lista_libros_PrestadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Lista_libros_PrestadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Max_Lista_librosCompletedEventHandler(object sender, Max_Lista_librosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Max_Lista_librosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Max_Lista_librosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ConsultaCompletedEventHandler(object sender, ConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void DevolucionCompletedEventHandler(object sender, DevolucionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevolucionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevolucionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591